rules:

  unpinned-images:
    ignore:
      - dotnet-build-test.yml
      - node-build-test.yml
      - playwright-tests.yml
      - playwright-report.yml

  unpinned-uses:
    ignore:
      - acceptance-gate.yml

  artipacked:
    ignore:
      - release-please.yml

  excessive-permissions:
    ignore:
      - playwright-tests.yml
      - playwright-docker-tests.yml
