rules:

  unpinned-uses:
    config:
      policies:
        "ianoflynnautomation/bjjeire-ci-templates/*": ref-pin
        "*": hash-pin

  unpinned-images:
    ignore:
      - dotnet-build-test.yml
      - node-build-test.yml
      - playwright-tests.yml
      - playwright-report.yml

  artipacked:
    ignore:
      - release-please.yml

  excessive-permissions:
    ignore:
      - playwright-tests.yml
      - playwright-docker-tests.yml
