
name: Release

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  release:
    name: Release Please
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/release-please.yml
    with:
      release-type: simple
      move-major-tag: true
